### ISSUE TITLE
echo 1 >/proc/sys/fs/filemon2/trigger has no Effect Flushing dirty Dentries to Kernel Event Log File

### ISSUE THREAD

**Issue by juergenc** [schoebel/filemon2#5]
### Release
```sh
cat /proc/version 
Linux version 4.4.185-icpu-025-g6ffde592baba (root@mini-buildd-3) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #2 SMP Wed Jul 17 07:24:14 UTC 2019
```

#### Enforcing by writing into `/proc/sys/fs/filemon2/trigger`
1. Have a monitored Filemonitor II partition in place, with standard values (no extra *.conf files in `.filemon2/` directory)
1. `cd fm2/partition/root`
1. Touch a file on FM2-partition-root every two seconds: `while sleep 2; do touch xy; done`
1. We will find - of course - an event entry in the currently opened kernel event log file:
```sh
less +F .filemon2/eventlog-000003357.log
event_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# LOGROT_END       1568970326.921233648 1579524650.813946884
1579524871.775111592 1579524871.775111592 8000 8000 1 19113 1285332784 283 /xy
# LOGROT_BEGIN     1568970326.921233648 1579525257.305061034
```
1. We want to enforce a flush of the dirty dentries written back to kernel event log file: `echo 1 > /proc/sys/fs/filemon2/trigger`
1. Nothing will happen, the expected dirty event is not written back to kernel event log file, even you execute the previous command a second time
1. After subsequent kernel event logrotate we expect the dirty event is written back on current event log file before close, but there is none:
```sh
less +F .filemon2/eventlog-000003358.log
event_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# LOGROT_END       1568970326.921233648 1579525257.305061034
```

**Comment by schoebel** [comment]
Hi Jürgen,

according to the docs section 2.3, you need to create a small control file extra-timeout-fm2.cmd (or some other *.cmd control) _before_ pushing the trigger.

If you only press the trigger button without prior creation of *.cmd, nothing will happen. This method was negoriated with Andrei some years ago, in order to avoid busy-wait scanning by the kernel.

I have forgotten to mention in the docs that a _combination_ of *.cmd with the trigger is needed. I will publish a doc update soon.
